server:
  port: 8080
  servlet:
    context-path: /challenge/api/v1


spring:
  datasource:
    url: jdbc:h2:mem:domusdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework: DEBUG
    domus.challenge: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs       # Path for the OpenAPI JSON
  swagger-ui:
    path: /swagger-ui.html   # Path for the Swagger UI
    operationsSorter: method # Sort operations by HTTP method
    tagsSorter: alpha        # Sort tags alphabetically
    display-request-duration: true    # Show request duration in Swagger UI
    doc-expansion: none               # Collapse all endpoints by default
    disable-swagger-default-url: true # Disable default Swagger URL