server:
  port: 8080
  servlet:
    context-path: /challenge/api/v1


spring:
  datasource:
    url: jdbc:h2:mem:domusdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework: DEBUG
    domus.challenge: DEBUG


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /meta/s
      exposure:
        include: "*"